export const MBTI_Nodon_Descriptions = [
  {
    MBTI: "INFJ",
    Nodon: "Mermaid",
    Blurb1: "Sings in .wav, thinks in .json",
    Blurb2: "Adds sparkle shaders to ethics",
    Description: "Your entire life is wired through an invisible AND-Nodon of destiny. You hand-craft moral quests while humming the GBG title-screen music and leaving a trail of bioluminescent TODO comments. Most mortals can’t keep up with your underwater TED talks.",
    FriendlyNodon: "Alien",
    ArchNodon: "Fluffball",
  },
  {
    MBTI: "INFP",
    Nodon: "Chick",
    Blurb1: "Soft-boiled philosopher",
    Blurb2: "Peeping out poetry in Morse code",
    Description: "You hatch side-quests for kindness, then wander off to re-texture the sunset. Every cable from your Emotion Nodon feeds directly into the 🐣 ‘Aww’ compiler. Friends adore you; evil bosses get scrambled.",
    FriendlyNodon: "Cheerleader",
    ArchNodon: "UFO",
  },
  {
    MBTI: "INTJ",
    Nodon: "Sorceress",
    Blurb1: "500-IQ spell macros",
    Blurb2: "Runs ‘future.exe’ on boot",
    Description: "You stockpile logic nodons like mana crystals, then execute 10-step plans while everyone else is still calibrating the gyro. Cloaked in dry sarcasm + violet particle effects, you always know which trigger will end the level.",
    FriendlyNodon: "Diver",
    ArchNodon: "Fish",
  },
  {
    MBTI: "INTP",
    Nodon: "Alien",
    Blurb1: "Breakpoint set at reality",
    Blurb2: "Debugs the cosmos for fun",
    Description: "You materialised after someone accidentally connected a NOT Nodon to a Wormhole Nodon. Now you roam the sandbox, poking variables and leaving conspiracy whiteboards in your wake. The universe is open-source; you’re reading the comments.",
    FriendlyNodon: "Sorceress",
    ArchNodon: "Mermaid",
  },
  {
    MBTI: "ISFJ",
    Nodon: "UFO",
    Blurb1: "Introverted Flying Object",
    Blurb2: "Beams up everyone’s worries",
    Description: "You hover quietly at 30 fps, tractor-beaming lost hopes back into inventory. Your auto-save aura means nobody’s progress ever vanishes. If drama appears, you activate the ‘blanket-of-warm-light’ shader and peace resumes.",
    FriendlyNodon: "Robot",
    ArchNodon: "Traveler",
  },
  {
    MBTI: "ISFP",
    Nodon: "Fish",
    Blurb1: "Silent but artsy splash",
    Blurb2: "Communicates via bubble-particle FX",
    Description: "You paint the seabed with chromatic aberration, then swim away before the credits roll. Small talk? Nah. You’d rather rig an elegant swim cycle and let the animation express your feels at 60 fps.",
    FriendlyNodon: "Tuna",
    ArchNodon: "Alien",
  },
  {
    MBTI: "ISTJ",
    Nodon: "Robot",
    Blurb1: "Runs on clock-cycle hugs",
    Blurb2: "Alignment: STRICT TRUE",
    Description: "Your wiring diagram is tidier than the GBG dev docs. Processes execute, bugs vanish, and the coffee timer resets precisely at frame 2400. Chaos glitches when you step in—exactly as designed.",
    FriendlyNodon: "UFO",
    ArchNodon: "Chick",
  },
  {
    MBTI: "ISTP",
    Nodon: "Diver",
    Blurb1: "Fixes leaks mid-dive",
    Blurb2: "Carbon-fibre chill mode",
    Description: "When something breaks, you just equip a wrench Nodon, hold ZR, and patch it before anyone screams ‘help!’ Your mantra: ‘Try it, see if it floats.’ Spoiler: it does, because you tuned the buoyancy.",
    FriendlyNodon: "Chick",
    ArchNodon: "Tuna",
  },
  {
    MBTI: "ENFJ",
    Nodon: "Yeti",
    Blurb1: "Hugs so big they have hit-boxes",
    Blurb2: "Leads the cut-scene with vibes",
    Description: "You stride into the overworld, toss confetti particles, and everybody’s morale bar jumps to max HP. Your secret power is mapping every friend to the perfect output port—even the NPCs start volunteering.",
    FriendlyNodon: "Person",
    ArchNodon: "Diver",
  },
  {
    MBTI: "ENFP",
    Nodon: "Traveler",
    Blurb1: "Spawns checkpoints on whims",
    Blurb2: "Collects side-quests like stickers",
    Description: "You fast-travel from idea to idea via portals made of caffeine. Dialogue trees bloom wherever you stand, and your inventory is 80% dreams, 20% souvenir snow-globes. Tutorial? Nah, you’ll wing it.",
    FriendlyNodon: "Mermaid",
    ArchNodon: "Person",
  },
  {
    MBTI: "ENTJ",
    Nodon: "Tuna",
    Blurb1: "Speedrun CEO mode",
    Blurb2: "Dash cancels through meetings",
    Description: "You swim so fast the water asks for backlog grooming. Sprint planning = literal sprint, because you timed it and found 0.7 s cheaper. Others draft OKRs; you draft tidal waves.",
    FriendlyNodon: "Sumo Wrestler",
    ArchNodon: "Sorceress",
  },
  {
    MBTI: "ENTP",
    Nodon: "Hippo",
    Blurb1: "Chaos physics enabled",
    Blurb2: "Jokes per minute: 9000",
    Description: "Your mouth is mapped to a random-idea generator with zero cooldown. You’ll attach a rocket Nodon to literally anything just to see if it jukes the gravity engine. Debate you? Good luck keeping frame rate.",
    FriendlyNodon: "Traveler",
    ArchNodon: "Hippo",
  },
  {
    MBTI: "ESFJ",
    Nodon: "Fluffball",
    Blurb1: "Throws comfort like confetti",
    Blurb2: "Restores HP with cookies",
    Description: "You emit a 30-meter radius buff that auto-heals social awkwardness. Your particle effect is ‘fresh-baked aroma’. If friends hit low stamina, you spawn a picnic cut-scene until the squad is back to full hearts.",
    FriendlyNodon: "Yeti",
    ArchNodon: "Robot",
  },
  {
    MBTI: "ESFP",
    Nodon: "Cheerleader",
    Blurb1: "Frame-perfect hype combos",
    Blurb2: "Speaks fluent OMG!!!",
    Description: "Push any button and you fire a glitter cannon. Even the option menu becomes a dance floor. You’re the only Nodon who can set the FPS to ‘fun per second’.",
    FriendlyNodon: "Chick",
    ArchNodon: "Sumo Wrestler",
  },
  {
    MBTI: "ESTJ",
    Nodon: "Person",
    Blurb1: "Project-manager DLC unlocked",
    Blurb2: "Checks boxes before they exist",
    Description: "You carry a clipboard sprite everywhere and somehow it grants +10 productivity to the whole server. If a task escapes, you lasso it with a Logic Cable and file a status report before breakfast.",
    FriendlyNodon: "Fluffball",
    ArchNodon: "Cheerleader",
  },
  {
    MBTI: "ESTP",
    Nodon: "Sumo Wrestler",
    Blurb1: "YOLO is an input event",
    Blurb2: "Throws self at problem, solves it",
    Description: "Your gameplay loop: enter arena, press B to shout, press A to body-slam the obstacle into orbit. You once patched a bug by suplexing the Error Nodon. QA still has nightmares.",
    FriendlyNodon: "Yeti",
    ArchNodon: "Sorceress",
  },
];
