export const MBTI_Nodon_Descriptions = [
  {
    MBTI: "INFJ",
    Nodon: "Mermaid",
    Blurb1: "Sees the world beneath the surface",
    Blurb2: "",
    Description: `You see what others pass by—feel what others leave untouched. Like the Mermaid, you drift through quiet waters, seeking what lies beneath the surface. You listen with your whole heart, and speak with deep empathy.`,
    FriendlyNodon: "Chick",
    ArchNodon: "Tuna",
  },
  {
    MBTI: "INFP",
    Nodon: "Chick",
    Blurb1: "Dreaming softly of the sky above",
    Blurb2: "",
    Description: `Hopeful and kind with dreams bigger than the Nodon limit, you carry warmth like a feather in the wind. You may be small or soft-spoken, but your ambitions are much larger. Your ideas may take time to hatch — but one day, they will be able to fly.`,
    FriendlyNodon: "Mermaid",
    ArchNodon: "Diver",
  },
  {
    MBTI: "INTJ",
    Nodon: "Sorceress",
    Blurb1: "Every spell is pre-written",
    Blurb2: "",
    Description: `Disciplined and deliberate, you cast your plans like pre-charged spells. Like the Sorceress, you ride your broom with certainty—no wizard that there is or was can ever pull you down. No need for divination — you already know what’s coming.`,
    FriendlyNodon: "Robot",
    ArchNodon: "Cheerleader",
  },
  {
    MBTI: "INTP",
    Nodon: "Alien",
    Blurb1: "Sees more than what meets the eye",
    Blurb2: "",
    Description: `Endlessly curious and quietly offbeat, you see the world through a lens no one else quite has. Like the Alien, you’re an odd swirl of questions, patterns, and sideways logic that never stops bobbing. You’re not otherworldly on purpose... it just comes naturally.`,
    FriendlyNodon: "Hippo",
    ArchNodon: "Fluffball",
  },
  {
    MBTI: "ISFJ",
    Nodon: "UFO",
    Blurb1: "Always watching from above",
    Blurb2: "",
    Description: `Gentle and quietly protective, you hover where you're needed most. Like the UFO, you don't make a fuss—but you never miss a thing. You’re the unseen shield, always watching from above.`,
    FriendlyNodon: "Fluffball",
    ArchNodon: "Sumo",
  },
  {
    MBTI: "ISFP",
    Nodon: "Fish",
    Blurb1: "Swims gently through the noise",
    Blurb2: "",
    Description: `You wade through life with subtle flair and quiet charm. Like the Fish, you're expressive without saying a word, following your own creative current no matter how noisy the world gets.`,
    FriendlyNodon: "Chick",
    ArchNodon: "Tuna",
  },
  {
    MBTI: "ISTJ",
    Nodon: "Robot",
    Blurb1: "Always humming in the background",
    Blurb2: "",
    Description: `Steady, methodical, and low-key essential. Like the Robot, you’re the background process that never crashes. Even when others forget you’re there, you're always keeping everything on track.`,
    FriendlyNodon: "Sorceress",
    ArchNodon: "Traveler",
  },
  {
    MBTI: "ISTP",
    Nodon: "Person",
    Blurb1: "The one you always return to",
    Blurb2: "",
    Description: `Reliable, resourceful, and surprisingly expressive when it counts. Like the Person, you may look blank at first, but you’re the go-to in every scene—an unsung favorite, ready for anything.`,
    FriendlyNodon: "Diver",
    ArchNodon: "Hippo",
  },
  {
    MBTI: "ENFJ",
    Nodon: "Yeti",
    Blurb1: "Heart as big as its footprints",
    Blurb2: "",
    Description: `Loud when you need to be, soft where it counts. Like the Yeti, you lead with emotion and walk with impact, always keeping others in mind—especially when they can’t keep up.`,
    FriendlyNodon: "Fluffball",
    ArchNodon: "Alien",
  },
  {
    MBTI: "ENFP",
    Nodon: "Traveler",
    Blurb1: "Wanders with purpose",
    Blurb2: "",
    Description: `Your path may zigzag, but your direction always comes from the heart. Like the Traveler, you carry stories, questions, and spare connections—ready wherever the road takes you.`,
    FriendlyNodon: "Cheerleader",
    ArchNodon: "Robot",
  },
  {
    MBTI: "ENTJ",
    Nodon: "Tuna",
    Blurb1: "Surges through the tide",
    Blurb2: "",
    Description: `Nothing slows you down. Like the Tuna, you're sleek, sharp, and on the move—no hesitation, no Undos. You set the pace. Others just try to keep up.`,
    FriendlyNodon: "Diver",
    ArchNodon: "Mermaid",
  },
  {
    MBTI: "ENTP",
    Nodon: "Hippo",
    Blurb1: "Pops up where you least expect",
    Blurb2: "",
    Description: `You’re a surprise every time. Like the Hippo, you break the surface with a grin and a scheme, just when it starts to feel predictable. You don't just challenge expectations—you laugh as you break them.`,
    FriendlyNodon: "Alien",
    ArchNodon: "Person",
  },
  {
    MBTI: "ESFJ",
    Nodon: "Fluffball",
    Blurb1: "Emotional support ball",
    Blurb2: "",
    Description: `You're soft, sweet, and absolutely essential. Like the Fluffball, you might not do much mechanically—but emotionally? You hold the whole world together.`,
    FriendlyNodon: "UFO",
    ArchNodon: "Alien",
  },
  {
    MBTI: "ESFP",
    Nodon: "Cheerleader",
    Blurb1: "Always cheering for you!",
    Blurb2: "",
    Description: `You're all sparkle, motion, and contagious energy. Like the Cheerleader, you light up the room, reminding everyone to smile and to keep going. Every high-five, pompom shake, and midair spin is a power-up—and fun is never optional.`,
    FriendlyNodon: "Traveler",
    ArchNodon: "Sorceress",
  },
  {
    MBTI: "ESTJ",
    Nodon: "Diver",
    Blurb1: "Pressure’s fine when you’re prepared",
    Blurb2: "",
    Description: `Clarity, control, and careful execution—that’s your game. Like the Diver, you jump into challenges with gear tightened, goals locked, and zero margin for bugs. Where others hesitate, you dive deep, ready to troubleshoot on the fly.`,
    FriendlyNodon: "Person",
    ArchNodon: "Chick",
  },
  {
    MBTI: "ESTP",
    Nodon: "Sumo Wrestler",
    Blurb1: "Every moment’s a spotlight",
    Blurb2: "",
    Description: `You don't tiptoe in—you make your presence known. Like the Sumo Wrestler, you tackle everything head-on, turning every moment into a spotlight and every challenge into a match worth winning.`,
    FriendlyNodon: "Tuna",
    ArchNodon: "UFO",
  },
];
